// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/18/2026, 10:27:52 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/devesh/Devesh_Personal/devesh-wedding-card/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/devesh/Devesh_Personal/devesh-wedding-card/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/devesh/Devesh_Personal/devesh-wedding-card/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/devesh/Devesh_Personal/devesh-wedding-card/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/devesh/Devesh_Personal/devesh-wedding-card/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/devesh/Devesh_Personal/devesh-wedding-card/plugins/**/*.{js,ts,mjs}","/home/devesh/Devesh_Personal/devesh-wedding-card/composables/**/*.{js,ts,mjs}","/home/devesh/Devesh_Personal/devesh-wedding-card/utils/**/*.{js,ts,mjs}","/home/devesh/Devesh_Personal/devesh-wedding-card/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/devesh/Devesh_Personal/devesh-wedding-card/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/devesh/Devesh_Personal/devesh-wedding-card/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;